/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sprint1;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Aluno
 */
public class ProjetoUm extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoUm
     */
    public ProjetoUm() {
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ProjetoUm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ProjetoUm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ProjetoUm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ProjetoUm.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCpuMin = new javax.swing.JLabel();
        lblCpuMedia = new javax.swing.JLabel();
        lblCpuMaxima = new javax.swing.JLabel();
        lblCpU = new javax.swing.JLabel();
        lblDiscoMin = new javax.swing.JLabel();
        lblDiscoMedia = new javax.swing.JLabel();
        lblDiscoMaxima = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        lblMemória = new javax.swing.JLabel();
        lblMemoriaMin = new javax.swing.JLabel();
        lblMemoriaMedia = new javax.swing.JLabel();
        lblMemoriaMaxima = new javax.swing.JLabel();
        lblMinResulCpu = new javax.swing.JLabel();
        lblMedResulCpu = new javax.swing.JLabel();
        lblMaxResulCpu = new javax.swing.JLabel();
        lblMinResulDisco = new javax.swing.JLabel();
        lblMedResulDisco = new javax.swing.JLabel();
        lblMaxResulDisco = new javax.swing.JLabel();
        lblMinResulMemoria = new javax.swing.JLabel();
        lblMedResulMemoria = new javax.swing.JLabel();
        lblMaxResulMemoria = new javax.swing.JLabel();
        pgbCpu = new javax.swing.JProgressBar();
        pgbDisco = new javax.swing.JProgressBar();
        pgbMemoria = new javax.swing.JProgressBar();
        btnLeitura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMemText = new javax.swing.JLabel();
        lblDiscoText = new javax.swing.JLabel();
        lblCpuText = new javax.swing.JLabel();
        lblDisco1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Dados Leitura");

        lblCpuMin.setForeground(new java.awt.Color(255, 255, 255));
        lblCpuMin.setText("Minimo");

        lblCpuMedia.setForeground(new java.awt.Color(255, 255, 255));
        lblCpuMedia.setText("Média");

        lblCpuMaxima.setForeground(new java.awt.Color(255, 255, 255));
        lblCpuMaxima.setText("Máxima");

        lblCpU.setForeground(new java.awt.Color(255, 255, 255));
        lblCpU.setText("   CPU");

        lblDiscoMin.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscoMin.setText("Minimo");

        lblDiscoMedia.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscoMedia.setText("Média");

        lblDiscoMaxima.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscoMaxima.setText("Máxima");

        lblDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblDisco.setText("  Disco");

        lblMemória.setForeground(new java.awt.Color(255, 255, 255));
        lblMemória.setText("Memória");

        lblMemoriaMin.setForeground(new java.awt.Color(255, 255, 255));
        lblMemoriaMin.setText("Minimo");

        lblMemoriaMedia.setForeground(new java.awt.Color(255, 255, 255));
        lblMemoriaMedia.setText("Média");

        lblMemoriaMaxima.setForeground(new java.awt.Color(255, 255, 255));
        lblMemoriaMaxima.setText("Máxima");

        lblMinResulCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblMinResulCpu.setText("0");

        lblMedResulCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblMedResulCpu.setText("0");

        lblMaxResulCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxResulCpu.setText("0");

        lblMinResulDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblMinResulDisco.setText("0");

        lblMedResulDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblMedResulDisco.setText("0");

        lblMaxResulDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxResulDisco.setText("0");

        lblMinResulMemoria.setForeground(new java.awt.Color(255, 255, 255));
        lblMinResulMemoria.setText("0");

        lblMedResulMemoria.setForeground(new java.awt.Color(255, 255, 255));
        lblMedResulMemoria.setText("0");

        lblMaxResulMemoria.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxResulMemoria.setText("0");

        pgbCpu.setBackground(new java.awt.Color(204, 204, 255));
        pgbCpu.setForeground(new java.awt.Color(0, 51, 204));
        pgbCpu.setStringPainted(true);

        pgbDisco.setBackground(new java.awt.Color(204, 204, 255));
        pgbDisco.setForeground(new java.awt.Color(0, 51, 204));
        pgbDisco.setStringPainted(true);

        pgbMemoria.setBackground(new java.awt.Color(204, 204, 255));
        pgbMemoria.setForeground(new java.awt.Color(0, 51, 204));
        pgbMemoria.setMaximum(8);
        pgbMemoria.setStringPainted(true);

        btnLeitura.setText("Fazer leitura dos dados");
        btnLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeituraActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("8GB");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("100%");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("100%");

        lblMemText.setForeground(new java.awt.Color(255, 255, 255));

        lblDiscoText.setForeground(new java.awt.Color(255, 255, 255));

        lblCpuText.setForeground(new java.awt.Color(255, 255, 255));

        lblDisco1.setForeground(new java.awt.Color(255, 255, 255));
        lblDisco1.setText("  CPU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMemoriaMin)
                                    .addComponent(lblMinResulMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMemoriaMedia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMemoriaMaxima))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMedResulMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMaxResulMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblMinResulCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCpuMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMedResulCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCpuMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCpuMaxima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMaxResulCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMinResulDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMedResulDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMaxResulDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDiscoMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDiscoMedia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDiscoMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblMemText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblDiscoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(lblCpuText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnLeitura)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(pgbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)))
                                .addGap(356, 356, 356))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDisco1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(369, 369, 369)
                                .addComponent(lblCpU, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(lblMemória, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(lblDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(lblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpuMin)
                    .addComponent(lblCpuMedia)
                    .addComponent(lblCpuMaxima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinResulCpu)
                    .addComponent(lblMedResulCpu)
                    .addComponent(lblMaxResulCpu))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscoMin)
                    .addComponent(lblDiscoMedia)
                    .addComponent(lblDiscoMaxima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinResulDisco)
                    .addComponent(lblMedResulDisco)
                    .addComponent(lblMaxResulDisco))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemoriaMin)
                    .addComponent(lblMemoriaMedia)
                    .addComponent(lblMemoriaMaxima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinResulMemoria)
                    .addComponent(lblMedResulMemoria)
                    .addComponent(lblMaxResulMemoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblCpU))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblDisco1)))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCpuText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDisco)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDiscoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMemória)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pgbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMemText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnLeitura)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Integer contador=0;
    Random one=new Random();
    Random two=new Random();
    Random tree=new Random();
    Integer mediacpu=0, mediadisco=0, mediamemoria=0;   
    private void btnLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeituraActionPerformed
        // TODO add your handling code here:
        //Memoria 8GB
        //cpu
        //disco
        contador++;

        //        CPU
        {
            Integer cpu=one.nextInt(100);
            String cputex=String.valueOf(cpu);
            String min=lblMinResulCpu.getText();
            String max=lblMaxResulCpu.getText();
            Integer varCpuMin= Integer.valueOf(min);
            Integer varCpuMax= Integer.valueOf(max);            //        Integer varCpuMed= Integer.valueOf(lblCpuMedia.getText());

            if(varCpuMax<=cpu ){
                lblMaxResulCpu.setText(cputex);
                if(contador==1){
                    lblMinResulCpu.setText(cputex);
                }

            }
            else if(varCpuMin>cpu){
                lblMinResulCpu.setText(cputex);
            }
            pgbCpu.setMaximum(100);
            pgbCpu.setValue(cpu);
            pgbCpu.setMinimum(0);

            mediacpu =(mediacpu + cpu)/contador;
            String med=String.valueOf(mediacpu);
            lblMedResulCpu.setText(med);
            lblCpuText.setText(cputex);
        }
        //        DISCO
        {
            Integer disco=two.nextInt(100);
            String discotex=String.valueOf(disco);
            String min=lblMinResulDisco.getText();
            String max=lblMaxResulDisco.getText();
            Integer varDiscoMin= Integer.valueOf(min);
            Integer varDiscoMax= Integer.valueOf(max);            //        Integer varCpuMed= Integer.valueOf(lblCpuMedia.getText());

            if(varDiscoMax<=disco ){
                lblMaxResulDisco.setText(discotex);
                if(contador==1){
                    lblMinResulDisco.setText(discotex);
                }

            }
            else if(varDiscoMin>disco){
                lblMinResulDisco.setText(discotex);
            }

            pgbDisco.setValue(disco);
            mediadisco=(mediadisco+disco)/contador;
            String med=String.valueOf(mediadisco);
            lblMedResulDisco.setText(med);
            lblDiscoText.setText(discotex);
        }

        //          MEMORIA
        {
            Integer memoria=tree.nextInt(9);
            String memoriatex=String.valueOf(memoria);
            String min=lblMinResulMemoria.getText();
            String max=lblMaxResulMemoria.getText();
            Integer varMemoriaMin= Integer.valueOf(min);
            Integer varMemoriaMax= Integer.valueOf(max);            //        Integer varCpuMed= Integer.valueOf(lblCpuMedia.getText());

            if(varMemoriaMax<=memoria ){
                lblMaxResulMemoria.setText(memoriatex);
                if(contador==1){
                    lblMinResulMemoria.setText(memoriatex);
                }

            }
            else if(varMemoriaMin>memoria){
                lblMinResulMemoria.setText(memoriatex);
            }
            pgbMemoria.setValue(memoria);

            mediamemoria = (mediamemoria+ memoria)/contador;
            String med=String.valueOf(mediamemoria);
            lblMedResulMemoria.setText(med);
            lblMemText.setText(memoriatex);
    }//GEN-LAST:event_btnLeituraActionPerformed
  
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoUm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoUm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeitura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpU;
    private javax.swing.JLabel lblCpuMaxima;
    private javax.swing.JLabel lblCpuMedia;
    private javax.swing.JLabel lblCpuMin;
    private javax.swing.JLabel lblCpuText;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblDisco1;
    private javax.swing.JLabel lblDiscoMaxima;
    private javax.swing.JLabel lblDiscoMedia;
    private javax.swing.JLabel lblDiscoMin;
    private javax.swing.JLabel lblDiscoText;
    private javax.swing.JLabel lblMaxResulCpu;
    private javax.swing.JLabel lblMaxResulDisco;
    private javax.swing.JLabel lblMaxResulMemoria;
    private javax.swing.JLabel lblMedResulCpu;
    private javax.swing.JLabel lblMedResulDisco;
    private javax.swing.JLabel lblMedResulMemoria;
    private javax.swing.JLabel lblMemText;
    private javax.swing.JLabel lblMemoriaMaxima;
    private javax.swing.JLabel lblMemoriaMedia;
    private javax.swing.JLabel lblMemoriaMin;
    private javax.swing.JLabel lblMemória;
    private javax.swing.JLabel lblMinResulCpu;
    private javax.swing.JLabel lblMinResulDisco;
    private javax.swing.JLabel lblMinResulMemoria;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JProgressBar pgbCpu;
    private javax.swing.JProgressBar pgbDisco;
    private javax.swing.JProgressBar pgbMemoria;
    // End of variables declaration//GEN-END:variables
}
